name: MeriWaynePhotography
favicon: null
layout_spectrum: 0.8101693170610815
typography_spectrum: 0.40464733028784394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7480980006512254
  lightness: 0.22182911913841963
  saturation: 0.5666233627125621
  rhythmicContrast: 0.21733414893969893
purpose: []
